image: fdulwich/oskar-ci:cuda-11.3-3

stages:
  - build and test
  - doc
  - publish

.reports: &ready_reports
  - mkdir -p build/reports/

build-test-debug:
  stage: build and test
  tags: [k8srunner-gpu]
  before_script:
    - *ready_reports
    - nvidia-smi
    - mkdir debug
    - cd debug/
    - cmake ../ -DCOVERAGE_REPORT=ON -DCUDA_ARCH=6.1
  script:
    - make -j
    - ./apps/oskar_system_info
    - make coverage
  after_script:
    - mv debug/coverage.xml build/reports/code-coverage.xml
    - mv debug/coverage/ ./
  artifacts:
    paths:
      - build/
      - coverage/
    reports:
      cobertura: build/reports/code-coverage.xml

build-test-release:
  stage: build and test
  tags: [k8srunner-gpu]
  before_script:
    - *ready_reports
    # We need CMake >= 3.21.0 for the --output-junit option on CTest.
    - cmake --version
    - nvidia-smi
    - mkdir release
    - cd release/
    - cmake ../ -DCUDA_ARCH=6.1
  script:
    - make -j
    - ctest --output-junit unit-tests.xml
  after_script:
    - mv release/unit-tests.xml build/reports/
  artifacts:
    paths:
      - build/
    reports:
      junit: build/reports/unit-tests.xml

build-docs:
  stage: doc
  before_script:
    - mkdir build-docs && cd build-docs/
    - cmake ..
  script:
    - make doc_html
  artifacts:
    paths:
      - build-docs/doc/_build/html/
    expire_in: 3600 seconds

docker-release:
  stage: publish
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  variables:
    GIT_VERSION: $CI_COMMIT_SHORT_SHA
  before_script:
    - apk add make git
    - cd docker
    - echo $CAR_OCI_REGISTRY_USERNAME
    - echo $CI_COMMIT_TAG
    - echo $CAR_OCI_REGISTRY_PASSWORD | docker login --username $CAR_OCI_REGISTRY_USERNAME --password-stdin $CAR_OCI_REGISTRY_HOST
  script:
    - docker build -t artefact.skao.int/oskar-base-dep oskar-base-dep/
    - docker build -t artefact.skao.int/oskar-base -t artefact.skao.int/oskar-base:$CI_COMMIT_TAG oskar-base/
    - docker build -t artefact.skao.int/oskar-python3 -t artefact.skao.int/oskar-python3:$CI_COMMIT_TAG oskar-python3/
    - docker push artefact.skao.int/oskar-python3:$CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'

singularity-release:
  stage: publish
  before_script:
    - mkdir build && cd build/
    - cmake ..
    - export MY_VER=`cmake -LA -N . | grep OSKAR_VERSION_LONG | awk '{split($0,a,"="); print a[2]}'`
    - cd ../singularity/
  script:
    - singularity build OSKAR-base-dep.sif Singularity.base-dep
    - singularity build OSKAR-base.sif Singularity.base
    - singularity build OSKAR-${MY_VER}-Python3.sif Singularity.python3
    - mv OSKAR-${MY_VER}-Python3.sif ../
  artifacts:
    paths:
      - *.sif
    expire_in: 3600 seconds
# rules:
#   - if: '$CI_COMMIT_TAG'

pages:
  stage: publish
  image: alpine
  dependencies:
    - build-docs
    - build-test-debug
  script:
    - rm -rf public
    - mkdir -p public
    - mv coverage/ public/
    - mv build-docs/doc/_build/html/* public/
  artifacts:
    paths:
      - public
#    expire_in: never

# Create Gitlab CI badges from CI metrics
# https://developer.skao.int/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/post_step.yml'
